<?php

return [
    'vegetables' => [
        'sections' => [
            'slider_section',
            'top_right_banner_section',
            'category_section',
            'middle_banner_section',
            'flash_section',
            'featuers_section',
            'tab_section',
            'cta_section_status',
            'bottom_left_banner_section',
            'top_rated_section',
            'top_selling_section',
            'footer_section',
            'copyright_section',
        ],
    ],
    'furniture' => [
        'sections' => [
            'slider_section',
            'top_middle_banner_section',
            'category_section',
            'flash_section',
            'video_banner_section',
            'tab_section',
            'middle_banner_section',
            'cta_section_status',
            'top_rated_section',
            'bottom_middle_banner_section',
            'top_selling_section',
            'footer_section',
            'copyright_section',
        ],
    ],
    'fashion' => [
        'sections' => [
            'slider_section',
            'middle_banner_section',
            'category_section',
            'flash_section',
            'tab_section',
            'video_banner_section',
            'featuers_section',
            'footer_section',
            'copyright_section',
        ],
    ],
    'electronics' => [
        'sections' => [
            'slider_section',
            'top_right_banner_section',
            'featuers_section',
            'category_section',
            'flash_section',
            'middle_banner_section',
            'left_banner_section',
            'categoryProduct_section',
            'tab_section',
            'bottom_left_banner_section',
            'latest_product_section',
            'cta_section_status',
            'footer_section',
            'copyright_section',
        ],
    ],
    'kids' => [
        'sections' => [
            'slider_section',
            'category_section',
            'flash_section',
            'middle_right_banner_section',
            'categoryProduct_section',
            'left_banner_section',
            'middle_banner_section',
            'tab_section',
            'video_banner_section',
            'latest_product_section',
            'footer_section',
            'copyright_section',
        ],
    ],
    'manti' => [
        'sections' => [
            'slider_section',
            'featuers_section',
            'category_section',
            'flash_section',
            'featured_section',
            'middle_banner_section',
            'top_rated_section',
            'right_banner_section',
            'cta_section_status',
            'footer_section',
            'copyright_section',
        ],
    ],
    'pet' => [
        'sections' => [
            'hero_section',
            'category_section',
            'flash_section',
            'middle_banner_section',
            'featuers_section',
            'featured_section',
            'right_banner_section',
            'left_banner_section',
            'top_rated_section',
            'footer_section',
            'copyright_section',
        ],
    ],
    'skinflow' => [
        'sections' => [
            'hero_section',
            'category_section',
            'flash_section',
            'cta_section_status',
            'middle_banner_section',
            'featured_section',
            'right_banner_section',
            'left_banner_section',
            'top_rated_section',
            'footer_section',
            'copyright_section',
        ],
    ],
    'jewellery' => [
        'sections' => [
            'hero_section',
            'featuers_section',
            'category_section',
            'flash_section',
            'middle_banner_section',
            'featured_section',
            'right_banner_section',
            'left_banner_section',
            'top_selling_section',
            'footer_section',
            'copyright_section',
        ],
    ],
];
